export  const ActionTypes = {
    SET_PICTURES: "SET_PICTURES",
    SET_DIFFERENTS: "SET_DIFFERENTS",
    SELECTED_PICTURE: "SELECTED_PICTURE",
    SELECTED_DIFFERENT: "SELECTED_DIFFERENT",
    REMOVE_SELECTED_PICTURE: "REMOVE_SELECTED_PICTURE",
    FOUND_ITEM: "FOUND_ITEM"
}